name: macos

on:
  push:            # run on push events
    paths-ignore:  # but ignore everything in the docs subfolder
      - 'docs/**'
    branches:
      - '**'
    tags:
      - '*'
  pull_request:    # run on pull requests
    paths-ignore:  # but ignore everything in the docs subfolder
      - 'docs/**'
  schedule:
    - cron:  '5 2 * * *'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    env:
      CCACHE_COMPILERTYPE: clang

    steps:
    - name: Cloning SUMO
      uses: actions/checkout@v4
      with:
        path: sumo
        fetch-depth: 0

    - name: Preparing Build System
      run: |
        brew update
        brew upgrade || brew link --overwrite python@3.12
        brew install --cask xquartz
        brew install xerces-c fox proj gdal gl2ps ccache googletest fmt
#        python3 -m pip install texttest

    - name: ccache
      if: github.event_name != 'schedule'
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Building SUMO
      run: |
        mkdir -p sumo/cmake-build
        cd sumo/cmake-build
        cmake ..
        make -j4

    - name: Building Traas
      run: |
        cd sumo/cmake-build
        make traas

    - name: Installing SUMO
      run: |
        cd sumo/cmake-build
        sudo make install

    - name: Building Examples and Tests
      run: |
        cd sumo/cmake-build
        make CTEST_OUTPUT_ON_FAILURE=1 examples test

    - name: Uploading artifacts (SUMO binaries and FMU)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-binaries
        path: sumo/bin

    - name: Creating macOS installer dmg
      run: |
        cd sumo
        python3 -m pip install dmgbuild
        python3 tools/build_config/buildMacOSInstaller.py ./cmake-build

    - name: Uploading macOS installer dmg
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-installer-unsigned
        path: sumo/sumo-*.dmg
